# Generated by Django 5.1 on 2024-08-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_transaction_portfolio_book_delete_portfolio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='book',
            name='name',
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Want to Read', 'Want to Read'), ('Reading', 'Reading'), ('Read', 'Read')], max_length=50),
        ),
    ]
